### PR TITLE
Fixes google drive upload

### LINKED ISSUE #14: Google Drive: RedirectMissingLocation
```
Last full backup is too old, forcing full backup
Attempt 1 failed. RedirectMissingLocation: Redirected but the response is missin
g a Location: header.
Attempt 2 failed. RedirectMissingLocation: Redirected but the response is missin
g a Location: header.
Attempt 3 failed. RedirectMissingLocation: Redirected but the response is missin
g a Location: header.
Attempt 4 failed. RedirectMissingLocation: Redirected but the response is missin
g a Location: header.
Giving up after 5 attempts. RedirectMissingLocation: Redirected but the response
 is missing a Location: header.
```

Seems to be a well known error. Should be fixed relatively easily by switching versions of the underlying drive library. I confirmed that the image tagged as blacklabelops/volumerize:1.5.1 as of today (d9ddc01511af) is working as expected.

This issue was also posted in:
https://github.com/blacklabelops/volumerize/issues/86#issue-852128262

### PR DESCRIPTION
**Pull request by Miladiir**
Fixes #14

### CODE REVIEW

**Comment by Miladiir** [comment]
Not sure how to bump versions, you guys may need to step in.

**Comment by sargreal** [comment]
Hey @Miladiir 

what you suggest seems to work, i would however rather state the version requirement directly when installing, something like this:
```diff
diff --git a/Dockerfile b/Dockerfile
index 5201fb7..310f9e9 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -43,6 +43,7 @@ RUN apk upgrade --update && \
     pip3 install --no-cache-dir wheel setuptools-scm && \
     pip3 install --no-cache-dir \
       fasteners \
+      google-api-python-client>=2.2.0 \
       PyDrive \
       chardet \
       azure-storage-blob \
```

**Comment by Miladiir** [comment]
I agree, much more elegant. I updated the pull request.

**Comment by sargreal** [comment]
Thanks, it looks good to me :)

**Pull request merged**
